# Imorting pandas

In [2]:
import pandas as pd
import numpy as np

# Pandas Data Frames

# Creating pandas data frames

# (01) Using dictionaries

In [8]:
details={"Name":["Jane","David","Kane","Sammie","Jack"],"Age":[32,27,43,45,24],"Gender":["F","M","M","F","M"]}
details

{'Name': ['Jane', 'David', 'Kane', 'Sammie', 'Jack'],
 'Age': [32, 27, 43, 45, 24],
 'Gender': ['F', 'M', 'M', 'F', 'M']}

In [7]:
df1 = pd.DataFrame(details)
df1

Name  Age Gender
0    Jane   32      F
1   David   27      M
2    Kane   43      M
3  Sammie   45      F
4    Jack   24      M

# (02) Using numpy arrays

In [23]:
arr=np.array([[12,24],[23,15],[34,37]])
arr

array([[12, 24],
       [23, 15],
       [34, 37]])

In [10]:
df2 = pd.DataFrame(arr, columns= ["col1","col2"])

In [11]:
df2

col1  col2
0    12    24
1    23    15
2    34    37

# (03) Creating data frames using CSV files 

In [16]:
df3 = pd.read_csv("/Users/kanishkarathnayake/Downloads/Arc Downloads/Iris dataset.csv") #import csv file

In [17]:
df3

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [20]:
type(df1)

pandas.core.frame.DataFrame

In [21]:
type(df2)

pandas.core.frame.DataFrame

In [22]:
type(df3)

pandas.core.frame.DataFrame

# Top values of the data set

In [24]:
df3.head() #first five rows

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [33]:
df3.head(3) #needed number of rows

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

# Bottom values of the data set

In [28]:
df3.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [29]:
df3.tail(7)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [30]:
details=pd.DataFrame({"Name":["Jane","David","Kane","Sammie","Jack"],"Age":[32,27,43,45,24],"Gender":["F","M","M","F","M"]})
details

Name  Age Gender
0    Jane   32      F
1   David   27      M
2    Kane   43      M
3  Sammie   45      F
4    Jack   24      M

In [31]:
details.head(2)

Name  Age Gender
0   Jane   32      F
1  David   27      M

In [32]:
details.tail(3)

Name  Age Gender
2    Kane   43      M
3  Sammie   45      F
4    Jack   24      M

# Description

In [34]:
df1.info

<bound method DataFrame.info of      Name  Age Gender
0    Jane   32      F
1   David   27      M
2    Kane   43      M
3  Sammie   45      F
4    Jack   24      M>

In [40]:
details.info

<bound method DataFrame.info of      Name  Age Gender
0    Jane   32      F
1   David   27      M
2    Kane   43      M
3  Sammie   45      F
4    Jack   24      M>

# Columns & indexes of the data set

In [41]:
df3.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [42]:
list(df3.columns) #convert into a list

['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Species']

In [43]:
df3.index

RangeIndex(start=0, stop=150, step=1)

In [44]:
list(df3.index) #convert and see as a list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149]

In [47]:
details=pd.DataFrame({"Name":["Jane","David","Kane","Sammie","Jack"],
                      "Age":[32,27,43,45,24],"Gender":["F","M","M","F","M"]},
                    index=["a", "b", "c", "d", "e"])
details

Name  Age Gender
a    Jane   32      F
b   David   27      M
c    Kane   43      M
d  Sammie   45      F
e    Jack   24      M

In [48]:
details.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

# Shape of the data frame

In [50]:
df3.shape #will give the number of rows and columns

(150, 5)

In [51]:
details.shape

(5, 3)

# Data type of columns

In [87]:
details["Age"].dtype

dtype('int64')

# Separating data types in data frames

In [53]:
df3.info

<bound method DataFrame.info of      Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [56]:
dff = df3.select_dtypes(include = float)
dff.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

# (05) Creating data frames using Excel files

In [57]:
df4 = pd.read_excel("/Users/kanishkarathnayake/Downloads/Arc Downloads/DS Masterclass Excel Data.xlsx")

In [58]:
df4

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [59]:
df4.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [61]:
df4 = pd.read_excel("/Users/kanishkarathnayake/Downloads/Arc Downloads/DS Masterclass Excel Data.xlsx", sheet_name= "marks")
df4

ID  Marks
0   1     67
1   2     78
2   3     76
3   4     66
4   5     89

In [66]:
ef = pd.ExcelFile("/Users/kanishkarathnayake/Downloads/Arc Downloads/DS Masterclass Excel Data.xlsx") #open excel file

In [67]:
ef.sheet_names #get the sheet names

['iris', 'marks']

In [82]:
dff = ef.parse("iris")
dff.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# Adding new columns

In [83]:
df=pd.DataFrame({"Col1":[12,22,23,34,45],"Col2":[45,43,44,46,54],"Col3":[56,43,46,67,65]})
df

Col1  Col2  Col3
0    12    45    56
1    22    43    43
2    23    44    46
3    34    46    67
4    45    54    65

# Accessing columns & elements

In [84]:
df=pd.DataFrame({"Col1":[12,22,23,34,45],"Col2":[45,43,44,46,54],"Col3":[56,43,46,67,65]})
df

Col1  Col2  Col3
0    12    45    56
1    22    43    43
2    23    44    46
3    34    46    67
4    45    54    65

# Accessing columns

In [86]:
df["Col1"]

0    12
1    22
2    23
3    34
4    45
Name: Col1, dtype: int64

# Accessing elements

In [88]:
df=pd.DataFrame({"Col1":[12,22,23,34,45],"Col2":[45,43,44,46,54],"Col3":[56,43,46,67,65]})

In [89]:
df

Col1  Col2  Col3
0    12    45    56
1    22    43    43
2    23    44    46
3    34    46    67
4    45    54    65

In [91]:
df.iloc[1,2]

43

In [92]:
df.iloc[2:4, :2]

Col1  Col2
2    23    44
3    34    46

In [93]:
df.iloc[: , 1]

0    45
1    43
2    44
3    46
4    54
Name: Col2, dtype: int64

In [94]:
df.iloc[3,:]  #all the values of 3rd row

Col1    34
Col2    46
Col3    67
Name: 3, dtype: int64

In [96]:
df.iat[1,2]  #same output with iat

43

In [97]:
df.at[1, "Col2"] #when there's a need to use column name instead of index number

43

# Converting to arrays

In [ ]:
df=pd.DataFrame({"Col1":[12,22,23,34,45],"Col2":[45,43,44,46,54],"Col3":[56,43,46,67,65]})

In [98]:
df

Col1  Col2  Col3
0    12    45    56
1    22    43    43
2    23    44    46
3    34    46    67
4    45    54    65

In [99]:
df.values #converts this to array

array([[12, 45, 56],
       [22, 43, 43],
       [23, 44, 46],
       [34, 46, 67],
       [45, 54, 65]])

In [100]:
df["Col1"].values

array([12, 22, 23, 34, 45])

# Basic column operations

In [101]:
data = np.arange(10).reshape(5,2)
df = pd.DataFrame(data,columns=["Col1","Col2"])
df

Col1  Col2
0     0     1
1     2     3
2     4     5
3     6     7
4     8     9

In [103]:
df["Col3"] = df["Col1"] + df["Col2"]    #Creating a new column by adding column 1 and 2 together
df

Col1  Col2  Col3
0     0     1     1
1     2     3     5
2     4     5     9
3     6     7    13
4     8     9    17

In [105]:
df["Col4"] = ["A" if i>=10 else "B" for i in df["Col3"] ]   #if value of col3 >= 10 append A else B to Col4
df

Col1  Col2  Col3 Col4
0     0     1     1    B
1     2     3     5    B
2     4     5     9    B
3     6     7    13    A
4     8     9    17    A

# Pandas data frames with apply function

In [106]:
data = np.arange(10).reshape(5,2)
df = pd.DataFrame(data,columns=["Col1","Col2"])
df

Col1  Col2
0     0     1
1     2     3
2     4     5
3     6     7
4     8     9

In [107]:
df.apply(sum, axis = 0)

Col1    20
Col2    25
dtype: int64

In [108]:
df.apply(sum, axis = 1)

0     1
1     5
2     9
3    13
4    17
dtype: int64

In [109]:
df.apply(len, axis = 1)

0    2
1    2
2    2
3    2
4    2
dtype: int64

In [110]:
df.apply(np.mean, axis = 1)

0    0.5
1    2.5
2    4.5
3    6.5
4    8.5
dtype: float64

In [9]:
df = pd.DataFrame({"English": [56,45,75,86,23] , "Maths": [67,85,92,39,63]})
df

English  Maths
0       56     67
1       45     85
2       75     92
3       86     39
4       23     63

In [10]:
fun = lambda L : "Pass" if np.mean(L) >= 50 else "Fail"

In [13]:
df["Results"]=df.apply(fun, axis = 1)

In [14]:
df

English  Maths Results
0       56     67    Pass
1       45     85    Pass
2       75     92    Pass
3       86     39    Pass
4       23     63    Fail

# Pandas data frames with map function

In [15]:
data = np.arange(10).reshape(5,2)
df = pd.DataFrame(data,columns=["Col1","Col2"])
df

Col1  Col2
0     0     1
1     2     3
2     4     5
3     6     7
4     8     9

In [16]:
fun = lambda x: 2*x

In [17]:
df["Col2"].map(fun)

0     2
1     6
2    10
3    14
4    18
Name: Col2, dtype: int64

In [ ]:
df=pd.DataFrame({"English":[45,54,57,46,58],"Maths":[42,54,57,41,76]})
df

# Selecting rows that have certain values

# Boolean masking technique

In [21]:
df=pd.DataFrame({"Name":["A","B","C","D","E","F"],"Age":[23,33,21,35,23,34],"Result":["Pass","Fail","Pass","Pass","Fail","Fail"]})
df

Name  Age Result
0    A   23   Pass
1    B   33   Fail
2    C   21   Pass
3    D   35   Pass
4    E   23   Fail
5    F   34   Fail

In [22]:
df["Age"] > 30   #takes the ones with age greater than 30

0    False
1     True
2    False
3     True
4    False
5     True
Name: Age, dtype: bool

In [24]:
df[df["Age"] > 30 ]  #same thing as a daraframe

Name  Age Result
1    B   33   Fail
3    D   35   Pass
5    F   34   Fail

In [25]:
df[df["Result"] == "Pass"]

Name  Age Result
0    A   23   Pass
2    C   21   Pass
3    D   35   Pass

In [26]:
df[(df["Result"] == "Pass") & (df["Age"] < 30)]

Name  Age Result
0    A   23   Pass
2    C   21   Pass

In [20]:
a = np.array([10,25,30,43,50])
b = np.array([8,21,26,40,51])

a < b

array([False, False, False, False,  True])

In [15]:
b%2 == 0

array([False, False, False, False, False])

In [21]:
(a > b) & (b%2 == 0)   #in arrays "and" operator wont work but the andpresent

array([ True, False,  True,  True, False])

# Selecting with map function

In [19]:
fun = lambda L : "Pass" in L

In [27]:
df["Result"].map(fun)

0     True
1    False
2     True
3     True
4    False
5    False
Name: Result, dtype: bool

# Pandas queries

In [29]:
df.query('Result == "Pass"')

Name  Age Result
0    A   23   Pass
2    C   21   Pass
3    D   35   Pass

In [30]:
df.query('Age >= 30')

Name  Age Result
1    B   33   Fail
3    D   35   Pass
5    F   34   Fail

# Data summaries

In [31]:
data=np.random.random(20).reshape(5,4)
data

array([[0.26980021, 0.64448647, 0.30194775, 0.85742681],
       [0.69601792, 0.81402733, 0.15756104, 0.59763087],
       [0.52631543, 0.94054352, 0.13727107, 0.29047419],
       [0.16660693, 0.37826242, 0.65775388, 0.02716612],
       [0.12243402, 0.70767897, 0.05401293, 0.08977159]])

In [32]:
df=pd.DataFrame(data,columns=["A","B","C","D"],index=["a","b","c","d","e"])
df

A         B         C         D
a  0.269800  0.644486  0.301948  0.857427
b  0.696018  0.814027  0.157561  0.597631
c  0.526315  0.940544  0.137271  0.290474
d  0.166607  0.378262  0.657754  0.027166
e  0.122434  0.707679  0.054013  0.089772

# Summaries for each column

In [33]:
df.describe()

A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.356235  0.697000  0.261709  0.372494
std    0.246207  0.210638  0.238715  0.350627
min    0.122434  0.378262  0.054013  0.027166
25%    0.166607  0.644486  0.137271  0.089772
50%    0.269800  0.707679  0.157561  0.290474
75%    0.526315  0.814027  0.301948  0.597631
max    0.696018  0.940544  0.657754  0.857427

# Summaries for each row

In [34]:
df.transpose().describe()

a         b         c         d         e
count  4.000000  4.000000  4.000000  4.000000  4.000000
mean   0.518415  0.566309  0.473651  0.307447  0.243474
std    0.282542  0.286499  0.349984  0.274544  0.310729
min    0.269800  0.157561  0.137271  0.027166  0.054013
25%    0.293911  0.487613  0.252173  0.131747  0.080832
50%    0.473217  0.646824  0.408395  0.272435  0.106103
75%    0.697722  0.725520  0.629872  0.448135  0.268745
max    0.857427  0.814027  0.940544  0.657754  0.707679

# Categorical columns

In [35]:
df=pd.DataFrame({"A":[23,34,21,45,67],"B":[45,24,67,88,67],"C":["a","a","b","b","a"]})
df

A   B  C
0  23  45  a
1  34  24  a
2  21  67  b
3  45  88  b
4  67  67  a

In [36]:
df.describe()    #only gives numerical summaries

A          B
count   5.000000   5.000000
mean   38.000000  58.200000
std    18.841444  24.427444
min    21.000000  24.000000
25%    23.000000  45.000000
50%    34.000000  67.000000
75%    45.000000  67.000000
max    67.000000  88.000000

In [37]:
df.describe(include="all") #gives all the summeries including categorical

A          B    C
count    5.000000   5.000000    5
unique        NaN        NaN    2
top           NaN        NaN    a
freq          NaN        NaN    3
mean    38.000000  58.200000  NaN
std     18.841444  24.427444  NaN
min     21.000000  24.000000  NaN
25%     23.000000  45.000000  NaN
50%     34.000000  67.000000  NaN
75%     45.000000  67.000000  NaN
max     67.000000  88.000000  NaN

# Finding sums for columns and rows separately

In [38]:
data=np.random.random(10).reshape(5,2)
data

array([[0.87335629, 0.2224082 ],
       [0.22462972, 0.99395328],
       [0.52575707, 0.7805906 ],
       [0.11538989, 0.45117943],
       [0.28188527, 0.6706923 ]])

In [39]:
df=pd.DataFrame(data,columns=["A","B"],index=["a","b","c","d","e"])
df

A         B
a  0.873356  0.222408
b  0.224630  0.993953
c  0.525757  0.780591
d  0.115390  0.451179
e  0.281885  0.670692

In [40]:
df.sum() #for columns

A    2.021018
B    3.118824
dtype: float64

In [41]:
df.sum(axis = 1)   #for rows

a    1.095764
b    1.218583
c    1.306348
d    0.566569
e    0.952578
dtype: float64

# Cumulative summaries

In [42]:
df.cumsum()

A         B
a  0.873356  0.222408
b  1.097986  1.216361
c  1.623743  1.996952
d  1.739133  2.448132
e  2.021018  3.118824

# Finding means for columns and rows separately

In [43]:
df.mean()

A    0.404204
B    0.623765
dtype: float64

In [44]:
df.mean(axis =1)

a    0.547882
b    0.609291
c    0.653174
d    0.283285
e    0.476289
dtype: float64

# Finding minumum and maximum for columns and rows separately

In [45]:
df.min()

A    0.115390
B    0.222408
dtype: float64

In [46]:
df.max()

A    0.873356
B    0.993953
dtype: float64

# Dropping rows & columns

In [47]:
df=pd.DataFrame({"Name":["A","B","C"],"Age":[23,33,21],"Result":["Pass","Fail","Pass"]},index=["a","b","c"])
df

Name  Age Result
a    A   23   Pass
b    B   33   Fail
c    C   21   Pass

# Dropping rows

In [49]:
df1 = df.drop("a")
df1

Name  Age Result
b    B   33   Fail
c    C   21   Pass

In [72]:
df

Name  Age Result
0    A   23   Pass
1    B   33   Fail
2    C   21   Pass

In [73]:
df.drop("b",inplace = True)
df

KeyError: "['b'] not found in axis"

In [65]:
df2=pd.DataFrame({"Name":["A","B","C"],"Age":[23,33,21],"Result":["Pass","Fail","Pass"]})
df2

Name  Age Result
0    A   23   Pass
1    B   33   Fail
2    C   21   Pass

In [66]:
df2.drop(1)

Name  Age Result
0    A   23   Pass
2    C   21   Pass

In [67]:
df2

Name  Age Result
0    A   23   Pass
1    B   33   Fail
2    C   21   Pass

# Dropping columns

In [53]:
df=pd.DataFrame({"Name":["A","B","C"],"Age":[23,33,21],"Result":["Pass","Fail","Pass"]},index=["a","b","c"])
df

Name  Age Result
a    A   23   Pass
b    B   33   Fail
c    C   21   Pass

In [77]:
df.drop("Name", axis = 1)

Age Result
0   23   Pass
1   33   Fail
2   21   Pass

# Sorting data frames with column values

In [78]:
d={"Name":["Sam","Jane","Kane"],"Mark1":[67,54,44],"Mark2":[56,56,67],"Mark3":[78,89,76]}
df=pd.DataFrame(d)
df

Name  Mark1  Mark2  Mark3
0   Sam     67     56     78
1  Jane     54     56     89
2  Kane     44     67     76

In [79]:
df.sort_values(by ="Mark1")

Name  Mark1  Mark2  Mark3
2  Kane     44     67     76
1  Jane     54     56     89
0   Sam     67     56     78

In [80]:
df.sort_values(by ="Mark1",ascending = False)

Name  Mark1  Mark2  Mark3
0   Sam     67     56     78
1  Jane     54     56     89
2  Kane     44     67     76

# Grouping data frames with categorical data

In [83]:
d={"ID":[1001,1002,1003,1004,1005],"Age":[23,33,34,24,25],"Gender":["F","F","M","F","M"],"Marks":[67,69,76,74,90]}
df=pd.DataFrame(d)
df

ID  Age Gender  Marks
0  1001   23      F     67
1  1002   33      F     69
2  1003   34      M     76
3  1004   24      F     74
4  1005   25      M     90

In [84]:
df.sort_values(by ="Gender")  #sort alphabetical order

ID  Age Gender  Marks
0  1001   23      F     67
1  1002   33      F     69
3  1004   24      F     74
2  1003   34      M     76
4  1005   25      M     90

In [85]:
g = df.groupby("Gender")

In [86]:
list(g)

[('F',
       ID  Age Gender  Marks
  0  1001   23      F     67
  1  1002   33      F     69
  3  1004   24      F     74),
 ('M',
       ID  Age Gender  Marks
  2  1003   34      M     76
  4  1005   25      M     90)]

In [87]:
g1 = list(g)

In [88]:
g1[0]

('F',
      ID  Age Gender  Marks
 0  1001   23      F     67
 1  1002   33      F     69
 3  1004   24      F     74)

In [89]:
g1[1]

('M',
      ID  Age Gender  Marks
 2  1003   34      M     76
 4  1005   25      M     90)

# Using generators

In [98]:
x = df.groupby("Gender").__iter__()

In [99]:
x.__next__()

('F',
      ID  Age Gender  Marks
 0  1001   23      F     67
 1  1002   33      F     69
 3  1004   24      F     74)

In [100]:
x.__next__()

('M',
      ID  Age Gender  Marks
 2  1003   34      M     76
 4  1005   25      M     90)

# Selecting a specific group

In [101]:
d={"ID":[1001,1002,1003,1004,1005],"Age":[23,33,34,24,25],"Gender":["F","F","M","F","M"],"Marks":[67,69,76,74,90]}
df=pd.DataFrame(d)
df

ID  Age Gender  Marks
0  1001   23      F     67
1  1002   33      F     69
2  1003   34      M     76
3  1004   24      F     74
4  1005   25      M     90

In [102]:
df.groupby("Gender").get_group("F")

ID  Age Gender  Marks
0  1001   23      F     67
1  1002   33      F     69
3  1004   24      F     74

In [103]:
df.groupby("Gender").get_group("M")

ID  Age Gender  Marks
2  1003   34      M     76
4  1005   25      M     90

# Summaries for other variables with grouping

In [109]:
d={"ID":[1001,1002,1003,1004,1005],"Age":[23,33,34,24,25],"Gender":["F","F","M","F","M"],"Marks":[67,69,76,74,90]}
df=pd.DataFrame(d)
df

ID  Age Gender  Marks
0  1001   23      F     67
1  1002   33      F     69
2  1003   34      M     76
3  1004   24      F     74
4  1005   25      M     90

In [110]:
df.drop("ID", axis = 1, inplace = True)

In [111]:
df.groupby("Gender").mean()

Age  Marks
Gender                  
F       26.666667   70.0
M       29.500000   83.0

In [112]:
df.groupby("Gender").sum()

Age  Marks
Gender            
F        80    210
M        59    166

In [113]:
df.groupby("Gender")["Age"].sum()

Gender
F    80
M    59
Name: Age, dtype: int64

# Summarizing other variables with grouping by using multiple options

In [114]:
df.groupby("Gender")["Age"].agg(["sum", "min", "max", "mean", "median", "var"])   #summary for multiple options

sum  min  max       mean  median        var
Gender                                             
F        80   23   33  26.666667    24.0  30.333333
M        59   25   34  29.500000    29.5  40.500000

# Grouping with more than one columns

In [115]:
d={"Age":[23,33,34,24,25],"Gender":["F","F","M","F","M"],"Marks":[67,69,76,74,90],"University":["UOC","UOC","UOC","UOP","UOP"]}
df=pd.DataFrame(d)
df

Age Gender  Marks University
0   23      F     67        UOC
1   33      F     69        UOC
2   34      M     76        UOC
3   24      F     74        UOP
4   25      M     90        UOP

In [117]:
df.groupby(["University", "Gender"]).mean()

Age  Marks
University Gender             
UOC        F       28.0   68.0
           M       34.0   76.0
UOP        F       24.0   74.0
           M       25.0   90.0

# Concatenating data frames

In [ ]:
df1=pd.DataFrame(np.random.random((5,2)),columns=["A","B"])
df2=pd.DataFrame(np.random.random((5,2)),columns=["A","B"])
df3=pd.DataFrame(np.random.random((5,2)),columns=["C","D"])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

# Concatenating along the rows

# Concatenating along the columns

# Merging data frames

In [ ]:
df1=pd.DataFrame({"ID":[1,2,3,4],"Val1":[23,33,34,45]})
df2=pd.DataFrame({"ID":[3,4,5,6],"Val2":[56,32,67,65]})

In [ ]:
df1

In [ ]:
df2

# Focus on the common Ids

# Focus on the all Ids

# Focus on the left side data frame Ids

# Focus on the right side data frame Ids

# Using an indicator for showing how the tables are merged

# Merging based on more than one column

In [ ]:
df1=pd.DataFrame({"ID1":[1,2,3,4],"ID2":[7,8,9,10],"Val1":[23,33,34,45]})
df2=pd.DataFrame({"ID1":[2,3,5,6],"ID2":[8,9,10,11],"Val2":[56,32,67,65]})

In [ ]:
df1

In [ ]:
df2

# Counting values

In [ ]:
d={"Col1":["P","P","Q"],"Col2":["X","Y","Z"],"Col3":["A","B","C"]}
df=pd.DataFrame(d)
df

# Unique values in a column

In [ ]:
d={"Col1":["P","P","Q"],"Col2":["X","Y","Z"],"Col3":["A","B","C"]}
df=pd.DataFrame(d)
df

# Counting unique elements

# Replace values in data frame

In [ ]:
d={"Col1":["P","P","Q"],"Col2":["X","Y","Z"],"Col3":[3,6,8]}
df=pd.DataFrame(d)
df

# Stacking & Unstacking data frames

In [ ]:
d={"Col1":["P","P","Q"],"Col2":["X","Y","Z"],"Col3":[3,6,8]}
df=pd.DataFrame(d)

# Creating Pivot tables

In [ ]:
d={"Cat":["A","B","B","A","C","A","C","B"],"Val":[4,5,6,8,3,9,8,2]}
df=pd.DataFrame(d)

In [ ]:
d={"Cat":["A","B","B","A","C","A","C","B"],"Rank":["1","2","1","2","1","2","1","2"],"Val":[4,5,6,8,3,9,8,2]}
df=pd.DataFrame(d)

In [ ]:
d={"Cat":["A","B","B","A","C","A","C","B"],"Rank":["1","2","1","2","1","2","1","2"],
   "Val1":[4,5,6,8,3,9,8,2],"Val2":[6,4,7,9,3,5,9,2]}
df=pd.DataFrame(d)

# Binning

In [ ]:
d={"ID":[1001,1002,1003,1004,1005],"Marks":[78,88,45,67,59]}
df=pd.DataFrame(d)
df

In [ ]:
d={"ID":[1001,1002,1003,1004,1005],"Marks":[78,88,45,67,59]}
df=pd.DataFrame(d)
df

# Largest and smallest values in a column

In [ ]:
d={"Cat":["A","B","B","A","C","A","C","B"],"Rank":["1","2","1","2","1","2","1","2"],"Val":[4,5,6,8,3,9,8,2]}
df=pd.DataFrame(d)
df

# Working with indexes & columns

In [ ]:
d={"Name":["Sam","Pam","Jane"],"Marks":[56,32,78],"Class":[1,2,3]}
df=pd.DataFrame(d,index=["a","b","c"])
df

# Columns of the data frame

# Indexes of the data frame

# Changing the order of the rows

# Changing the order of the columns

# Renaming the indexes & columns

In [ ]:
d={"Name":["Sam","Pam","Jane"],"Marks":[56,32,78],"Class":[1,2,3]}
df=pd.DataFrame(d,index=["a","b","c"])
df

# Making indexes as a column

In [ ]:
d={"Name":["Sam","Pam","Jane"],"Marks":[56,32,78],"Class":[1,2,3]}
df=pd.DataFrame(d,index=["a","b","c"])
df

# Making a column as the index set

In [ ]:
d={"Name":["Sam","Pam","Jane"],"Marks":[56,32,78],"Class":[1,2,3]}
df=pd.DataFrame(d,index=["a","b","c"])
df

# Permutation & taking samples

In [ ]:
d={"A":np.arange(1,11),"B":np.random.random(10),"C":np.random.randn(10)}
df=pd.DataFrame(d)
df

# Method 01 - Taking a shuffled data frame

# Shuffling data

# Random sample

# Method 02 - Shuffling existing indexes

# Method 03 - Sample method

# Random sample

# Shuffling data frame

# Working with dates

# Converting strings to dates

In [ ]:
df = pd.DataFrame({'date': ['3/10/2000', '3/11/2000', '3/12/2000'],'value': [2, 3, 4]})
df

In [ ]:
df = pd.DataFrame({'date': ['3/10/2000', '3/11/2000', '3/12/2000'],'value': [2, 3, 4]})
df

In [ ]:
df = pd.DataFrame({'date': ['3-10-2000', '3-11-2000', '3-12-2000'],'value': [2, 3, 4]})
df

In [ ]:
df = pd.DataFrame({'date': ['2016-6-10 20:30:0','2016-7-1 19:45:30','2013-10-12 4:5:1'],'value': [2, 3, 4]})
df

# Assemble a datetime from multiple columns

In [ ]:
df = pd.DataFrame({'year': [2015, 2016],'month': [2, 3],'day': [4, 5]})
df

# Separate year, month, and day

In [ ]:
df = pd.DataFrame({'name': ['Tom', 'Andy', 'Lucas'],'DOB': ['08-05-1997', '04-28-1996', '12-16-1995']})
df

# Get more information